version: '3.8'

services:
  mongodb:
    image: mongo:6.0
    container_name: ares-mongodb
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: ares_db
    volumes:
      - ares_mongo_data:/data/db

volumes:
  ares_mongo_data:
